name: Build&Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: qemu install
        run: |
          sudo apt-get update && sudo apt-get install -yqq qemu-user-static
      - name: Docker
        run: |
          docker buildx ls
